# Generated by Django 5.0.6 on 2024-07-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('alternative_phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Submitproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=50)),
                ('bhk', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('bedroom', models.CharField(max_length=50)),
                ('kitchen', models.CharField(max_length=50)),
                ('hall', models.CharField(max_length=20)),
                ('bathroom', models.CharField(max_length=50)),
                ('balcony', models.CharField(max_length=50)),
                ('floorap', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField()),
                ('area_size', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('feature', models.CharField(default='', max_length=300)),
                ('img1', models.ImageField(default='', upload_to='Apartment/images')),
                ('img2', models.ImageField(default='', upload_to='Apartment/images')),
                ('img3', models.ImageField(default='', upload_to='Apartment/images')),
                ('img4', models.ImageField(default='', upload_to='Apartment/images')),
                ('img5', models.ImageField(default='', upload_to='Apartment/images')),
                ('floor_planimg', models.ImageField(default='', upload_to='Apartment/images')),
                ('status2', models.CharField(max_length=20)),
                ('groundfloorimg', models.ImageField(default='', upload_to='Apartment/images')),
                ('basementfloor', models.ImageField(default='', upload_to='Apartment/images')),
                ('isfeatured', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
