# Generated by Django 5.0.6 on 2024-08-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='propertyname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='ownername',
            field=models.CharField(default='', max_length=50),
        ),
    ]
